// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://gqeuctenwncwbxpekwsm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdxZXVjdGVud25jd2J4cGVrd3NtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4NDU5MjcsImV4cCI6MjA3MTQyMTkyN30.VplDO_lTHeru3j77dKQ26uG6QQW3DpaLzdtjItRIkcU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);